config/routes.rb
Rails.application.routes.draw do
  get 'job_application_currents/create'
  get 'job_application_archives/update'
  root 'static_pages#home'

  devise_for :users

  resources :users, only: [:show] do
    resources :job_applications do
      resources :job_informations
      resources :job_application_archives
      resources :job_application_currents
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :job_applications

  def get_job_applications(archived:, current:)
    job_applications.order(created_at: :desc).filter { |job| job.archived == archived && job.current == current }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :is_my_profile, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  private

  def is_my_profile
    unless current_user == User.find(params[:id])
      flash[:danger] = 'Vous ne pouvez pas accéder aux informations de ce compte'
      redirect_to :root
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% content_for :jumbotron do %>
  <div class="jumbotron">
    <div class="container">
      <h1> Espace personnel </h1>
      <p class="lead"> <%= @user.email %> </p>
    </div>
  </div>
<% end %>

<!-- container -->
<div class="container">

  <!-- row -->
  <div class="row">

    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"> Mes candidatures </h5>
          <p class="card-text"> Voir la liste de mes candidatures, ajouter de nouvelles candidatures, ... </p>
          <%= link_to "Mes candidatures", user_job_applications_path(@user), class: "btn btn-primary" %>
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"> A venir </h5>
          <p class="card-text"> Plein de nouvelles fonctionnalités à venir </p>
          <%= link_to "Bientôt disponible...", root_path, class: "btn btn-primary disabled", disabled: true %>
        </div>
      </div>
    </div>

  </div>
  <!-- /row -->

</div>
<!-- /container -->