config/routes.rb
Rails.application.routes.draw do
  get 'job_application_currents/create'
  get 'job_application_archives/update'
  root 'static_pages#home'

  devise_for :users

  resources :users, only: [:show] do
    resources :job_applications do
      resources :job_informations
      resources :job_application_archives
      resources :job_application_currents
    end
  end
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :user
  has_many :job_informations

  validates :title, presence: true, allow_blank: false

  def sorted_job_informations
    job_informations.order(:created_at)
  end
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_my_profile

  def show
    @user = User.find(params[:user_id])
    @job_application = @user.job_applications.find(params[:id])
    @job_information = @job_application.job_informations.new
  end

  def index
    @user = User.find(params[:user_id])
    @job_applications = @user.job_applications.order(updated_at: :desc)
    @job_application = @user.job_applications.new
  end

  def create
    @user = User.find(params[:user_id])
    @job_application = @user.job_applications.new(job_application_params)
    if @job_application.save
      flash[:success] = 'Nouvelle candidature créée'
      redirect_to user_job_application_path(@user, @job_application)
    else
      render :index
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @job_application = @user.job_applications.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @job_application = @user.job_applications.find(params[:id])
    if @job_application.update(job_application_params)
      flash[:success] = 'Candidature modifiée'
      redirect_to user_job_application_path(@user, @job_application)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @job_application = @user.job_applications.find(params[:id])
    if @job_application.destroy
      flash[:success] = 'Candidature supprimée'
    else
      flash[:danger] = 'Une erreur est survenue'
    end
    redirect_to user_job_applications_path(@user)
  end

  private

  def is_my_profile
    unless current_user == User.find(params[:user_id])
      flash[:danger] = 'Vous ne pouvez pas accéder aux informations de ce compte'
      redirect_to :root
    end
  end

  def job_application_params
    permitted = params.require(:job_application).permit(:title)
  end
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/views/job_applications/_actions.html.erb
<div class="job-information row mb-4 job-application-actions">
  <hr class="my-2">
  <div class="col-lg-2 h2">
  </div>
  <div class="col-lg-10">
    <%= link_to "Ajouter une information", new_user_job_application_job_information_path(@user, @job_application), remote: true, class: "btn btn-primary btn-lg mr-4" %>
    <%= link_to "Modifier le titre", edit_user_job_application_path(@user, @job_application), class: "btn btn-secondary btn-lg mr-4" %>
    <% if @job_application.archived %>
      <%= link_to "Récupérer",  user_job_application_job_application_archives_path(@user, @job_application), method: :post, class: "btn btn-outline-info btn-lg mr-4" %>
    <% else %>
      <%= link_to "Archiver",  user_job_application_job_application_archives_path(@user, @job_application), method: :post, class: "btn btn-outline-secondary btn-lg mr-4" %>
    <% end %>
    <%= link_to "Supprimer", user_job_application_path(@user, @job_application), data: {confirm: "Etes-vous sûr ?"}, method: :delete, :class => "btn btn-outline-danger btn-lg" %>
  </div>
  <hr class="my-2">
</div>

app/views/job_applications/_form.html.erb
  <% if @job_application.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>La création de la candidatures n'a pu aboutir pour les raisons suivantes :</p>
    <ul>
      <% @job_application.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: [@user, @job_application], local: true do |form| %>

  <div class="form-group row">
    <div class="col-lg-9">
      <%= form.text_field :title, value: @job_application.title ? @job_application.title : "Titre du poste", class: "form-control"  %>
    </div>
    <div class="col-lg-3">
      <%= form.submit "Valider", class: "btn btn-outline-success btn-block" %>
    </div>
  </div>
<% end %>

app/views/job_applications/edit.html.erb
 <% content_for :jumbotron do %>
  <div class="jumbotron">
    <div class="container">
      <h1> Modifier la candidature </h1>
      <p class="lead"> Merci de remplir les renseignements suivants </p>
      <p class="lead">
        <%= link_to "Retour sur les candidatures", user_job_applications_path(@user), class: "btn btn-outline-primary btn-lg" %>
      </p>
    </div>
  </div>
<% end %>

<div class="container">

  <h1 class="mb-4"> Modifier le titre </h1>

  <%= render partial: 'form' %>

</div>

app/views/job_applications/index.html.erb
<% content_for :jumbotron do %>
  <div class="jumbotron">
    <div class="container">
      <h1> Mes candidatures </h1>
      <p class="lead"> Voir mes <%= @job_applications.size %> candidatures </p>
      <p class="lead d-flex">
        <%= link_to "Retour sur mon profil", user_path(@user), class: "btn btn-outline-primary btn-lg" %>
      </p>
    </div>
  </div>
<% end %>

<!-- container -->
<div class="container">

  <h1 class="mb-4"> Une nouvelle candidature ? </h1>

  <%= render partial: 'form' %>

  <h1 class="my-4"> En cours </h1>

  <!-- row -->
  <div class="row">

    <!-- job_application -->
    <% @user.get_job_applications(archived: false, current: true).each do |job_application| %>
      <div class="col-sm-6">
        <div class="card border-info text-info">
          <div class="card-body">
            <h5 class="card-title"> <%= job_application.title %> </h5>
            <p class="card-text">
              <%= l job_application.created_at %>
            </p>

            <div class="d-flex">
              <%= link_to "Détails...", user_job_application_path(@user, job_application), class: "btn btn-outline-info mr-auto" %>
              <%= link_to "Historique",  user_job_application_job_application_currents_path(@user, job_application), method: :post, class: "btn btn-outline-primary ml-2" %>
              <%= link_to "Archiver",  user_job_application_job_application_archives_path(@user, job_application), method: :post, class: "btn btn-outline-dark ml-2" %>
            </div>

          </div>
        </div>
      </div>
    <% end %>
    <!-- /job_application -->

  </div>
  <!-- /row -->

  <h1 class="my-4"> Mon historique </h1>

  <!-- row -->
  <div class="row">

    <!-- job_application -->
    <% @user.get_job_applications(archived: false, current: false).each do |job_application| %>
      <div class="col-sm-6">
        <div class="card border-primary text-primary">
          <div class="card-body">
            <h5 class="card-title"> <%= job_application.title %> </h5>
            <p class="card-text">
              <%= l job_application.created_at %>
            </p>

            <div class="d-flex">
              <%= link_to "Détails...", user_job_application_path(@user, job_application), class: "btn btn-outline-primary mr-auto" %>
              <%= link_to "En cours",  user_job_application_job_application_currents_path(@user, job_application), method: :post, class: "btn btn-outline-info ml-2" %>
              <%= link_to "Archiver",  user_job_application_job_application_archives_path(@user, job_application), method: :post, class: "btn btn-outline-dark ml-2" %>
            </div>

          </div>
        </div>
      </div>
    <% end %>
    <!-- /job_application -->

  </div>
  <!-- /row -->

  <h1 class="my-4"> Archives </h1>

  <!-- row -->
  <div class="row">

    <!-- job_application -->
    <% @user.get_job_applications(archived: true, current: false).each do |job_application| %>
      <div class="col-sm-6">
        <div class="card border-secondary text-secondary">
          <div class="card-body">
            <h5 class="card-title"> <%= job_application.title %> </h5>
            <p class="card-text">
              <%= l job_application.created_at %>
            </p>
            <div class="d-flex">

              <%= link_to "Détails...", user_job_application_path(@user, job_application), class: "btn btn-outline-secondary btn-block mr-auto" %>
              <%= link_to "Récupérer",  user_job_application_job_application_archives_path(@user, job_application), method: :post, class: "btn btn-outline-dark ml-2" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <!-- /job_application -->

  </div>
  <!-- /row -->

</div>
<!-- /container -->

app/views/job_applications/show.html.erb
<% content_for :jumbotron do %>
  <div class="jumbotron">
    <div class="container">
      <h1> <%= @job_application.title %> </h1>
      <p class="lead"> <%= l @job_application.updated_at %> </p>
      <p class="lead">
        <%= link_to "Retour sur les candidatures", user_job_applications_path(@user), class: "btn btn-outline-primary btn-lg" %>
      </p>
    </div>
  </div>
<% end %>

<div class="container">

  <% @job_application.sorted_job_informations.each do |job_information| %>
    <div id="job-information-<%= job_information.id %>">
      <% if job_information.id == @edit_job_information&.id %>
        <%= render partial: 'job_informations/form', locals: { job_information: @edit_job_information } %>
      <% else %>
        <%= render partial: 'job_informations/show', locals: { job_information: job_information } %>
      <% end %>
    </div>
  <% end %>

  <div id="job-information-form">
    <% if @new_job_information %>
      <%= render partial: 'job_informations/form', locals: { job_information:  @new_job_information } %>
    <% else %>
      <%= render partial: 'job_applications/actions' %>
    <% end %>
  </div>

  <div class="my-2"> </div>
</div>