config/routes.rb
Rails.application.routes.draw do
  get 'job_application_currents/create'
  get 'job_application_archives/update'
  root 'static_pages#home'

  devise_for :users

  resources :users, only: [:show] do
    resources :job_applications do
      resources :job_informations
      resources :job_application_archives
      resources :job_application_currents
    end
  end
end

app/models/job_information.rb
class JobInformation < ApplicationRecord
  belongs_to :job_application

  validates :name, presence: true, allow_blank: false
  validates :content, presence: true, allow_blank: false

  def content_html
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, extensions = {})
    markdown.render(content)
  end

  def init_with_url(url)
    parser = HtmlParser.new(url)
    content = parser.page_md
  end
end

app/controllers/job_informations_controller.rb
class JobInformationsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_my_profile

  def new
    @user = User.find(params[:user_id])
    @job_application = @user.job_applications.find(params[:job_application_id])
    @new_job_information = @job_application.job_informations.new
    respond_to do |format|
      format.html { render 'job_applications/show' }
      format.js {}
    end
  end

  def create
    @user = User.find(params[:user_id])
    @job_application = @user.job_applications.find(params[:job_application_id])
    @new_job_information = @job_application.job_informations.new(job_information_params)

    respond_to do |format|
      if @new_job_information.save
        format.html do
          flash[:success] = 'Nouvelle information ajoutée'
          redirect_to user_job_application_path(@user, @job_application)
        end
        format.js
      else
        format.html { render 'job_applications/show' }
        format.js { render 'job_informations/new' }
      end
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @job_application = @user.job_applications.find(params[:job_application_id])
    @edit_job_information = @job_application.job_informations.find(params[:id])
    respond_to do |format|
      format.html { render 'job_applications/show' }
      format.js {}
    end
  end

  def update
    @user = User.find(params[:user_id])
    @job_application = @user.job_applications.find(params[:job_application_id])
    @edit_job_information = @job_application.job_informations.find(params[:id])

    respond_to do |format|
      if params[:cancel]
        format.html do
          redirect_to user_job_application_path(@user, @job_application)
        end
        format.js
      elsif @edit_job_information.update(job_information_params)
        format.html do
          flash[:success] = 'Information modifiée'
          redirect_to user_job_application_path(@user, @job_application)
        end
        format.js
      else
        format.html { render 'job_applications/show' }
        format.js { render 'job_informations/edit' }
      end
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @job_application = @user.job_applications.find(params[:job_application_id])
    @destroy_job_information = @job_application.job_informations.find(params[:id])

    respond_to do |format|
      if @destroy_job_information.destroy
        format.html do
          flash[:success] = 'Information supprimée'
          redirect_to user_job_application_path(@user, @job_application)
        end
        format.js
      else
        format.html { render 'job_applications/show' }
      end
    end
  end

  private

  def is_my_profile
    unless current_user == User.find(params[:user_id])
      flash[:danger] = 'Vous ne pouvez pas accéder aux informations de ce compte'
      redirect_to :root
    end
  end

  def job_information_params
    permitted = params.require(:job_information).permit(:name, :content)
  end
end

app/helpers/job_informations_helper.rb
module JobInformationsHelper
end

app/views/job_informations/_form.html.erb
  <%= form_with model: [@user, @job_application, job_information] do |form| %>
  <div class="row">

    <div class="col-lg-2 h2">
      <%= form.text_field :name, class: "form-control"  %>
    </div>

    <div class="col-lg-10">
      <%= form.text_area :content, class: "form-control", rows: 9 %>

      <% if job_information.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p>La création n'a pu aboutir pour les raisons suivantes :</p>
          <ul>
            <% job_information.errors.full_messages.each do |message| %>
              <li> <%= message %> </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="d-flex">
        <%= form.submit "Valider", class: "btn btn-success btn-block col-lg-3" %>
        <%= button_tag "Annuler", type: "submit", name: "cancel", value: true, class: "btn btn-outline-secondary btn-block col-lg-3 ml-auto" %>
      </div>
    </div>
  </div>
<% end %>

<hr class="my-2">

app/views/job_informations/_show.html.erb
  
<div class="job-information row">
  <div class="col-lg-2">
    <h2> <%= job_information.name %> </h2>
  </div>
  <div class="col-lg-8">
    <%= raw job_information.content_html %>
    <%= job_information.created_at.strftime("%d - %m - %Y") %>
  </div>
  <div class="col-6 col-lg-1 h2">
    <%= link_to "Modif.", edit_user_job_application_job_information_path(@user, @job_application, job_information), remote: true, class: "btn btn-outline-primary btn-lg mr-4" %>
  </div>
  <div class="col-6 col-lg-1 h2">
    <%= link_to "Supp.", user_job_application_job_information_path(@user, @job_application, job_information), data: {confirm: "Etes-vous sûr ?"}, method: :delete, remote: true, :class => "btn btn-outline-danger btn-lg" %>
  </div>
</div>
<hr class="my-2">

app/views/job_informations/create.js.erb
function run() {
  let formAction = document.querySelector("div#job-information-form")
  formAction.innerHTML = ''
  formAction.insertAdjacentHTML('beforebegin', "<div id='job-information-<%= @new_job_information.id %>'><%= j render partial: 'job_informations/show', locals: { job_information: @new_job_information } %></div>")
  formAction.insertAdjacentHTML('afterbegin', "<%= j render partial: 'job_applications/actions' %>")
}

run()

app/views/job_informations/destroy.js.erb
function run() {
  let infoDiv = document.querySelector("div#job-information-<%= @destroy_job_information.id %>")
  infoDiv.remove()
}

run()

app/views/job_informations/edit.js.erb
function run() {
  let div = document.querySelector("div#job-information-<%= @edit_job_information.id %>")
  div.innerHTML = ''
  div.insertAdjacentHTML('afterbegin', "<%= j render partial: 'job_informations/form', locals: { job_information:  @edit_job_information } %>")
}

run()

app/views/job_informations/new.js.erb
function run() {
  let formAction = document.querySelector("div#job-information-form")
  formAction.innerHTML = ''
  formAction.insertAdjacentHTML('afterbegin', "<%= j render partial: 'job_informations/form', locals: { job_information:  @new_job_information } %>")
}

run()

app/views/job_informations/update.js.erb
function run() {

  let div = document.querySelector("div#job-information-<%= @edit_job_information.id %>")
  div.innerHTML = ''
  div.insertAdjacentHTML('afterbegin', "<%= j render partial: 'job_informations/show', locals: { job_information:  @edit_job_information } %>")
}

run()